---
# --- Assemble archives on controller and transfer to remote ---
- name: Assemble Gitea repositories backup on controller
  delegate_to: localhost
  run_once: true
  shell: |
    cat {{ playbook_dir }}/roles/gitea/files/gitea_repos.tar.gz.part.* \
      > /tmp/gitea_repos_backup.tar.gz
  args:
    executable: /bin/bash

- name: Transfer repositories backup to remote node
  copy:
    src: /tmp/gitea_repos_backup.tar.gz
    dest: /tmp/gitea_repos_backup.tar.gz

- name: Assemble Gitea database backup on controller
  delegate_to: localhost
  run_once: true
  shell: |
    cat {{ playbook_dir }}/roles/gitea/files/gitea_data.tar.gz.part.* \
      > /tmp/gitea_data_backup.tar.gz
  args:
    executable: /bin/bash

- name: Transfer database backup to remote node
  copy:
    src: /tmp/gitea_data_backup.tar.gz
    dest: /tmp/gitea_data_backup.tar.gz

# --- Gitea installation and restore ---
- name: Установить зависимости для Gitea (Debian)
  apt:
    name:
      - git
      - sqlite3
    state: present
  when: ansible_os_family == "Debian"

- name: Установить зависимости для Gitea (RedHat)
  yum:
    name:
      - git
      - sqlite
    state: present
  when: ansible_os_family == "RedHat"

- name: Скачать бинарный файл Gitea с помощью wget
  command: wget https://dl.gitea.com/gitea/1.23.6/gitea-1.23.6-linux-amd64 -O /usr/local/bin/gitea
  args:
    creates: /usr/local/bin/gitea
  become: yes

- name: Сделать бинарный файл Gitea исполняемым
  file:
    path: /usr/local/bin/gitea
    mode: '0755'
  become: yes

- name: Создать системного пользователя git
  user:
    name: git
    system: yes
    shell: /bin/bash
    create_home: yes

- name: Создать необходимые директории для Gitea
  file:
    path: "{{ item }}"
    state: directory
    owner: git
    group: git
    mode: '0755'
  loop:
    - /var/lib/gitea/custom
    - /var/lib/gitea/data
    - /var/lib/gitea/indexers
    - /var/lib/gitea/public
    - /var/lib/gitea/log

- name: Смонтировать GlusterFS том для Gitea
  mount:
    path: /var/lib/gitea/gitea-repositories
    src: "gitea-node-1:/gitea-repos"
    fstype: glusterfs
    opts: "defaults,_netdev,x-systemd.automount"
    state: mounted

- name: Обновить запись GlusterFS в /etc/fstab
  lineinfile:
    dest: /etc/fstab
    regexp: '^gitea-node-1:/gitea-repos'
    line: "gitea-node-1,gitea-node-2:/gitea-repos /var/lib/gitea/gitea-repositories glusterfs defaults,_netdev,x-systemd.automount 0 0"
  become: yes

- name: Создать директорию /etc/gitea
  file:
    path: /etc/gitea
    state: directory
    owner: git
    group: git
    mode: '0755'
  become: yes

- name: Разархивировать репозитории в GlusterFS
  unarchive:
    src: /tmp/gitea_repos_backup.tar.gz
    dest: "/var/lib/gitea/gitea-repositories"
    extra_opts: [--strip-components=1]
  become: yes

- name: Разархивировать базу данных
  unarchive:
    src: /tmp/gitea_data_backup.tar.gz
    dest: "/"
  become: yes

- name: Cleanup remote temporary backup files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /tmp/gitea_repos_backup.tar.gz
    - /tmp/gitea_data_backup.tar.gz
  become: yes

- name: Скопировать конфигурационный файл Gitea
  copy:
    src: roles/gitea/files/app.ini.backup
    dest: "/etc/gitea/app.ini"
  become: yes

- name: Обновить права на директории Gitea
  file:
    path: "{{ item }}"
    owner: git
    group: git
    recurse: yes
  loop:
    - "/var/lib/gitea"
    - "/etc/gitea"
  become: yes
  notify: Restart Gitea

- name: Создать systemd unit для Gitea
  copy:
    dest: /etc/systemd/system/gitea.service
    content: |
      [Unit]
      Description=Gitea (Git with a cup of tea)
      After=network.target

      [Service]
      User=git
      Group=git
      WorkingDirectory=/var/lib/gitea/
      ExecStart=/usr/local/bin/gitea web --config /etc/gitea/app.ini
      Restart=always
      Environment=USER=git HOME=/home/git GITEA_WORK_DIR=/var/lib/gitea

      [Install]
      WantedBy=multi-user.target
  notify: Restart Gitea

- name: Перезапустить и включить сервис Gitea
  systemd:
    name: gitea
    state: restarted
    enabled: yes
  become: yes

