---
- name: Установить Java 21
  apt:
    name: openjdk-21-jdk
    state: present
  become: yes
  when: ansible_os_family == "Debian"

- name: Установить Java 21 (RedHat)
  yum:
    name: java-21-openjdk
    state: present
  become: yes
  when: ansible_os_family == "RedHat"

- name: Настроить переменную JAVA_HOME для Jenkins
  lineinfile:
    path: /etc/default/jenkins
    regexp: '^JAVA_HOME='
    line: 'JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64'
    create: yes
  become: yes
  when: ansible_os_family == "Debian"

- name: Настроить переменную JENKINS_HOME для Jenkins
  lineinfile:
    path: /etc/default/jenkins
    regexp: '^JENKINS_HOME='
    line: 'JENKINS_HOME=/var/jenkins_home'
    create: yes
  become: yes

- name: Настроить переменную JAVA_HOME для Jenkins (RedHat)
  lineinfile:
    path: /etc/default/jenkins
    regexp: '^JAVA_HOME='
    line: 'JAVA_HOME=/usr/lib/jvm/java-21-openjdk'
    create: yes
  become: yes
  when: ansible_os_family == "RedHat"

- name: Убедиться, что директория для ключей существует
  file:
    path: /usr/share/keyrings
    state: directory
    mode: '0755'
  become: yes

- name: Задать переменные для GPG ключа Jenkins
  set_fact:
    # ИСПОЛЬЗУЕМ АКТУАЛЬНЫЙ URL КЛЮЧА (проверьте на pkg.jenkins.io, если есть сомнения)
    jenkins_key_url: "https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key"
    jenkins_keyring_path: "/usr/share/keyrings/jenkins-keyring.gpg"

- name: Удалить старый файл ключа Jenkins (для гарантии чистоты)
  file:
    path: "{{ jenkins_keyring_path }}"
    state: absent
  become: yes

- name: Скачать и добавить АКТУАЛЬНЫЙ GPG ключ Jenkins
  shell: >
    curl -fsSL {{ jenkins_key_url }} | gpg --dearmor -o {{ jenkins_keyring_path }} &&
    chmod 0644 {{ jenkins_keyring_path }}
  args:
    # Добавляем creates: обратно для идемпотентности после первого успешного скачивания
    creates: "{{ jenkins_keyring_path }}"
  register: download_key_result
  changed_when: download_key_result.rc == 0 # Можно упростить, полагаясь на creates
  become: yes

- name: Добавить репозиторий Jenkins с указанием ключа
  apt_repository:
    # Указываем путь к файлу ключа через signed-by
    repo: "deb [signed-by={{ jenkins_keyring_path }}] https://pkg.jenkins.io/debian-stable binary/"
    state: present
    filename: "jenkins" # Создаст /etc/apt/sources.list.d/jenkins.list
    update_cache: no 
  become: yes

- name: Очистить кеш APT перед обновлением (для решения проблем с кешем)
  shell: rm -rf /var/lib/apt/lists/* 2> /dev/null
  become: yes
  changed_when: false # Считаем, что сама очистка не меняет состояние системы с точки зрения идемпотентности

- name: Обновить кеш APT ПОСЛЕ очистки и добавления репозитория
  apt:
    update_cache: yes
    cache_valid_time: 0 # Принудительно обновить
  become: yes

- name: Установить Jenkins
  apt:
    name: jenkins
    state: present
  become: yes

- name: Настроить Jenkins Home на NFS
  mount:
    path: /var/jenkins_home
    src: "192.168.122.103:/var/jenkins_home"
    fstype: nfs
    opts: "defaults,_netdev"
    state: mounted
  become: yes

    #- name: Ensure key directory exists on Control Node
    # file:
    # path: "{{ playbook_dir }}/files" # Создаем директорию files внутри директории плейбука
    # state: directory
    #mode: '0700' # Права только для пользователя
    #connection: local # Выполнить локально на управляющей машине
    # run_once: true # Достаточно выполнить один раз для всего плейбука

- name: Сгенерировать SSH ключевую пару для Jenkins slave (если не существует)
  community.crypto.openssh_keypair:
    # Используем playbook_dir для надежности пути
    path: "{{ playbook_dir }}/roles/jenkins-master/files/jenkins-slave-id_rsa"
    type: rsa
    size: 4096
    mode: '0600' # Устанавливаем права на приватный ключ
  register: jenkins_keypair
  connection: local # Генерация ключа тоже локально
  run_once: true # Генерируем один раз

- name: Прочитать приватный SSH ключ Jenkins slave
  slurp:
    src: "{{ playbook_dir }}/roles/jenkins-master/files/jenkins-slave-id_rsa"
  register: jenkins_slave_key_raw
  connection: local # Чтение ключа тоже локально
  run_once: true # Читаем один раз

- name: Декодировать содержимое приватного ключа
  set_fact:
    jenkins_slave_ssh_key: "{{ jenkins_slave_key_raw.content | b64decode }}"

- name: Распаковать архив с Jenkins Home на целевом узле
  unarchive:
    src: "files/jenkins_home_backup.tar.gz"
    dest: /var/
    remote_src: no
  become: yes

- name: Сгенерировать JCasC конфигурацию для Jenkins
  template:
    src: jenkins.yaml.j2
    dest: /var/jenkins_home/jenkins.yaml
    owner: jenkins
    group: jenkins
    mode: '0644'
  become: yes
  delegate_to: 192.168.122.103

- name: Установить владельца файлов для Jenkins Home
  file:
    path: /var/jenkins_home
    owner: jenkins
    group: jenkins
    recurse: yes
  become: yes

- name: Создать директорию для override-файлов Jenkins в systemd
  file:
    path: /etc/systemd/system/jenkins.service.d
    state: directory
    mode: '0755'
  become: yes

- name: Создать override-файл для Jenkins с переменной JENKINS_HOME
  copy:
    dest: /etc/systemd/system/jenkins.service.d/override.conf
    content: |
      [Service]
      Environment="JENKINS_HOME=/var/jenkins_home"
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: Перезагрузить systemd для применения изменений
  command: systemctl daemon-reload
  become: yes

- name: Запустить Jenkins
  systemd:
    name: jenkins
    state: restarted
    enabled: yes
  become: yes
